services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=iflow_sentinel"
      - "MYSQL_PASSWORD=iflow_password"
      - "MYSQL_ROOT_PASSWORD=iflow_password"
      - "MYSQL_USER=iflow_user"
    ports:
      - "3306:3306"
