server:
    port: 8888

spring:
    application:
        name: iflow-sentinel
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: false

iflow-sentinel:
    security:
        credential-key: ${CREDENTIAL_ENCRYPTION_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

app:
    tenant:
        sync-cron: "0 */10 * * * *"
